

// auth actions 
export const SIGN_OUT = "SIGN_OUT"
export const SIGN_IN_WITH_GITHUB = "SIGN_IN_WITH_GITHUB"
export const SIGN_IN_ANONYMOUSLY = "SIGN_IN_ANONYMOUSLY"
export const GET_USER_STATE = "GET_USER_STATE"

 // api actions
export const GET_SEARCH_USER = "GET_SEARCH_USER"
export const GET_ALL_OWNER_REPOS = "GET_ALL_USER_REPOS"
export const GET_ALL_OWNER_ISSUES = "GET_ALL_OWNER_ISSUES"
export const GET_ALL_OWNER_REPO_ISSUES = "GET_ALL_OWNER_REPO_ISSUES"
export const GET_ONE_OWNER_ISSUE = "GET_ONE_OWNER_ISSUE"
export const GET_REPO_ISSUES_COMMENTS = "GET_REPO_ISSUES_COMMENTS"
export const GET_REPO_ISSUE_COMMENTS = "GET_REPO_ISSUE_COMMENTS"

// user actions
export const SELECT_USER = "SELECT_USER"